sudo: false
language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
env:
  - COMPOSER_NO_INTERACTION=1
install:
  - composer install
  - composer run setup-phpcs
script:
  - composer run lint
  - composer run syntax
